server:
  port: 9900
spring:
  application:
    name: spring-oauth2-app
security:
  oauth2:
    client:
      clientId: 785036948700474
      clientSecret: 3d10532c271c4e97ce9a44c7a060655a
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me
